#!/usr/bin/env ruby

irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

lib_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib'))

libs = []
libs << " -I #{lib_dir}"
libs << " -r irb/completion"
libs << " -r irb/ext/save-history"

libs <<  " -r #{File.dirname(__FILE__) + '/../lib/melon.rb'}"
puts "Loading melon gem"

exec "#{irb} #{libs} --simple-prompt"
